---
input:
  mode: "fasta_gff"
  fasta: "resources/input.fasta"
  gff3: "resources/input.gff3"
  contig_name: "test_plasmid"

igv_genome:
  id: "test_plasmid"
  name: "test_plasmid"

output_prefix: "results/bowtie2_index/combined"
